export const UPDATE_CURRENCY = 'UPDATE_CURRENCY';

//for Crypto Side bar
export const FETCH_SIDEBAR_DATA_BEGIN = 'FETCH_SIDEBAR_DATA_BEGIN';
export const FETCH_SIDEBAR_DATA_SUCCESS = 'FETCH_SIDEBAR_DATA_SUCCESS';
export const FETCH_SIDEBAR_DATA_FAILURE = 'FETCH_SIDEBAR_DATA_FAILURE';


export const SEARCH_CRYPTO_BEGIN = 'SEARCH_CRYPTO_BEGIN';
export const SEARCH_CRYPTO_SUCCESS = 'SEARCH_CRYPTO_SUCCESS';
export const SEARCH_CRYPTO_FALIURE = 'SEARCH_CRYPTO_FALIURE';

//for Crypto Drop Down 
export const FETCH_COINS_BEGIN = 'FETCH_COINS_BEGIN';
export const FETCH_COINS_SUCCESS = 'FETCH_COINS_SUCCESS';
export const FETCH_COINS_FAILURE = 'FETCH_COINS_FAILURE';

//for Market Data of Coins
export const FETCH_COIN_MARKET_DATA_START = 'FETCH_COIN_MARKET_DATA_START';
export const FETCH_COIN_MARKET_DATA_SUCCESS = 'FETCH_COIN_MARKET_DATA_SUCCESS';
export const FETCH_COIN_MARKET_DATA_FAILURE = 'FETCH_COIN_MARKET_DATA_FAILURE';

// Defining action types for fetching exchange rates
export const FETCH_EXCHANGE_RATES_REQUEST = "FETCH_EXCHANGE_RATES_REQUEST";
export const FETCH_EXCHANGE_RATES_SUCCESS = "FETCH_EXCHANGE_RATES_SUCCESS";
export const FETCH_EXCHANGE_RATES_FAILURE = "FETCH_EXCHANGE_RATES_FAILURE";
